[tool.poetry]
name = "django-pattern-library"
version = "0.2.4"
description = "A module for Django that allows to build pattern libraries for your projects."
authors = [
    "Mikalai Radchuk <mikalai.radchuk@torchbox.com>",
    "Ben Dickinson <ben.dickinson@torchbox.com>"
]
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Framework :: Django",
    "Framework :: Django :: 1.11",
    "Framework :: Django :: 2.0",
    "Framework :: Django :: 2.1",
    "Framework :: Django :: 2.2",
]
packages = [
    { include = "pattern_library" }
]

[tool.poetry.dependencies]
python = "^3.6"
Django = ">=1.11,<3"
PyYAML = "^5.1"

[tool.poetry.dev-dependencies]
beautifulsoup4 = "^4.8"
coverage = "^4.5"
flake8 = "^3.7"
isort = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
